/*
 * jCleaningSchedule - program for printing house cleaning schedules
 * Copyright (C) 2012  Martin Mareš <mmrmartin[at]gmail[dot]com>
 *
 * This file is part of jCleaningSchedule.
 *
 * jCleaningSchedule is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * jCleaningSchedule is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with jCleaningSchedule.  If not, see <http://www.gnu.org/licenses/>.
 */

package cz.martinmares.jcleaningschedule.gui;

import cz.martinmares.jcleaningschedule.print.GuiPrintCore;
import cz.martinmares.jcleaningschedule.print.PrintCore;
import javax.swing.SpinnerNumberModel;

/**
 * The print preview window of jCleaningSchedule.
 * @author Martin Mareš
 */
public class PrintPreviewFrame extends javax.swing.JDialog {

    GuiPrintCore printCore;
    
    /**
     * Creates new form PrintPreviewFrame
     */
    public PrintPreviewFrame(java.awt.Frame parent, boolean modal, 
            PrintCore inPrintCore) {
        super(parent, modal);
        //Components
        initComponents();
        //PrintCore
        printCore = (GuiPrintCore)inPrintCore;
        printCore.setParentComponent(this);
        //PagesCount
        jLabelMaxPage.setText(""+printCore.getNumberOfPages());
        ((SpinnerNumberModel)jSpinnerPage.getModel())
                .setMaximum(printCore.getNumberOfPages()); 
        //Page
        changePage(1);
    }
    
    public void changePage(int page) {
        swingCanvas1.setImage(printCore.getImg(page-1));
        jScrollPane1.getVerticalScrollBar().setValue(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonClose = new javax.swing.JButton();
        jButtonPrint = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSpinnerPage = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabelMaxPage = new javax.swing.JLabel();
        jButtonPageSetup = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        swingCanvas1 = new cz.martinmares.jcleaningschedule.gui.PrintPreviewCanvas();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("cz/martinmares/jcleaningschedule/resources/lang"); // NOI18N
        setTitle(bundle.getString("PRINT_PREVIEW")); // NOI18N

        jPanel1.setBorder(null);

        jButtonClose.setText(bundle.getString("DIALOG_CLOSE")); // NOI18N
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        jButtonPrint.setText(bundle.getString("PRINT")); // NOI18N
        jButtonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrintActionPerformed(evt);
            }
        });

        jLabel1.setText(bundle.getString("PAGE")); // NOI18N

        jSpinnerPage.setModel(new javax.swing.SpinnerNumberModel(1, 1, 1, 1));
        jSpinnerPage.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerPageStateChanged(evt);
            }
        });

        jLabel2.setText("/");

        jLabelMaxPage.setText("1");

        jButtonPageSetup.setText(bundle.getString("PAGE_SETUP")); // NOI18N
        jButtonPageSetup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPageSetupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinnerPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMaxPage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonPageSetup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonPrint)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonClose)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSpinnerPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jLabelMaxPage))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonClose)
                        .addComponent(jButtonPrint)
                        .addComponent(jButtonPageSetup)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        swingCanvas1.setPreferredSize(new java.awt.Dimension(595, 841));

        javax.swing.GroupLayout swingCanvas1Layout = new javax.swing.GroupLayout(swingCanvas1);
        swingCanvas1.setLayout(swingCanvas1Layout);
        swingCanvas1Layout.setHorizontalGroup(
            swingCanvas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 641, Short.MAX_VALUE)
        );
        swingCanvas1Layout.setVerticalGroup(
            swingCanvas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 841, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(swingCanvas1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrintActionPerformed
        if(printCore.printAll()) //If print is sucessful than close the window
            jButtonCloseActionPerformed(evt);        
    }//GEN-LAST:event_jButtonPrintActionPerformed

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jSpinnerPageStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerPageStateChanged
        changePage((int)jSpinnerPage.getValue());
    }//GEN-LAST:event_jSpinnerPageStateChanged

    private void jButtonPageSetupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPageSetupActionPerformed
        printCore.pageDialog();
        jSpinnerPageStateChanged(null);
    }//GEN-LAST:event_jButtonPageSetupActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonPageSetup;
    private javax.swing.JButton jButtonPrint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelMaxPage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerPage;
    private cz.martinmares.jcleaningschedule.gui.PrintPreviewCanvas swingCanvas1;
    // End of variables declaration//GEN-END:variables
}
